version: '3'
volumes:
    bbdd:
services:
    php:
        # image: 'php:7.2-fpm'
        build:
            context: ./docker
            dockerfile: php.Dockerfile
        container_name: php
        ports:
            - '9000:9000'
        volumes:
            - './app:/var/www/html'
            #- './appSencillo:/var/www/html'

 
    nginx:
        image: nginx:latest
        container_name: nginx
        ports:
            - '80:80'
            - '443:443'
        volumes:
            #- './appSencillo:/var/www/html'
            - './app:/var/www/html'
            - './config/nginx:/etc/nginx/conf.d'

    mariadb:
        image: mariadb:10.3.9
        container_name: mariadb
        restart: 'on-failure'
        ports:
            - '3306:3306'
        environment:
            MYSQL_ROOT_PASSWORD: bolson
        volumes:
            - ./bbdd:/var/lib/mysql

